# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created: Mon Oct 23 18:39:34 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1474, 1011)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_ = QtGui.QGridLayout()
        self.gridLayout_.setObjectName("gridLayout_")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_Comannds = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Comannds.sizePolicy().hasHeightForWidth())
        self.tabWidget_Comannds.setSizePolicy(sizePolicy)
        self.tabWidget_Comannds.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_Comannds.setObjectName("tabWidget_Comannds")
        self.tab_Project = QtGui.QWidget()
        self.tab_Project.setObjectName("tab_Project")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_Project)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_EndDate = QtGui.QLabel(self.tab_Project)
        self.label_EndDate.setObjectName("label_EndDate")
        self.gridLayout_4.addWidget(self.label_EndDate, 1, 0, 1, 1)
        self.comboBox_UserName = QtGui.QComboBox(self.tab_Project)
        self.comboBox_UserName.setEditable(True)
        self.comboBox_UserName.setObjectName("comboBox_UserName")
        self.gridLayout_4.addWidget(self.comboBox_UserName, 2, 1, 1, 1)
        self.label_SubDate = QtGui.QLabel(self.tab_Project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SubDate.sizePolicy().hasHeightForWidth())
        self.label_SubDate.setSizePolicy(sizePolicy)
        self.label_SubDate.setObjectName("label_SubDate")
        self.gridLayout_4.addWidget(self.label_SubDate, 0, 0, 1, 1)
        self.dateTimeEdit_start = QtGui.QDateTimeEdit(self.tab_Project)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.gridLayout_4.addWidget(self.dateTimeEdit_start, 0, 1, 1, 1)
        self.dateTimeEdit_end = QtGui.QDateTimeEdit(self.tab_Project)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.gridLayout_4.addWidget(self.dateTimeEdit_end, 1, 1, 1, 1)
        self.label_username = QtGui.QLabel(self.tab_Project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_username.sizePolicy().hasHeightForWidth())
        self.label_username.setSizePolicy(sizePolicy)
        self.label_username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_username.setObjectName("label_username")
        self.gridLayout_4.addWidget(self.label_username, 2, 0, 1, 1)
        self.label_ProjectName = QtGui.QLabel(self.tab_Project)
        self.label_ProjectName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ProjectName.setObjectName("label_ProjectName")
        self.gridLayout_4.addWidget(self.label_ProjectName, 3, 0, 1, 1)
        self.comboBox_ProjectName = QtGui.QComboBox(self.tab_Project)
        self.comboBox_ProjectName.setEditable(True)
        self.comboBox_ProjectName.setObjectName("comboBox_ProjectName")
        self.gridLayout_4.addWidget(self.comboBox_ProjectName, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.pushButton_Reloaduser = QtGui.QPushButton(self.tab_Project)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Reloaduser.sizePolicy().hasHeightForWidth())
        self.pushButton_Reloaduser.setSizePolicy(sizePolicy)
        self.pushButton_Reloaduser.setObjectName("pushButton_Reloaduser")
        self.gridLayout_2.addWidget(self.pushButton_Reloaduser, 1, 1, 1, 1)
        self.tabWidget_Comannds.addTab(self.tab_Project, "")
        self.tab_jobID = QtGui.QWidget()
        self.tab_jobID.setObjectName("tab_jobID")
        self.gridLayout = QtGui.QGridLayout(self.tab_jobID)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit_jobID = QtGui.QPlainTextEdit(self.tab_jobID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_jobID.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_jobID.setSizePolicy(sizePolicy)
        self.plainTextEdit_jobID.setMaximumSize(QtCore.QSize(200, 500))
        self.plainTextEdit_jobID.setPlainText("")
        self.plainTextEdit_jobID.setObjectName("plainTextEdit_jobID")
        self.gridLayout.addWidget(self.plainTextEdit_jobID, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_jobID)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget_Comannds.addTab(self.tab_jobID, "")
        self.verticalLayout_3.addWidget(self.tabWidget_Comannds)
        self.pushButton_Search = QtGui.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_Search.setFont(font)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.verticalLayout_3.addWidget(self.pushButton_Search)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_, 2, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_jobs = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jobs.sizePolicy().hasHeightForWidth())
        self.label_jobs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setWeight(75)
        font.setBold(True)
        self.label_jobs.setFont(font)
        self.label_jobs.setObjectName("label_jobs")
        self.verticalLayout_5.addWidget(self.label_jobs)
        self.tableWidget_jobList = QtGui.QTableWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_jobList.sizePolicy().hasHeightForWidth())
        self.tableWidget_jobList.setSizePolicy(sizePolicy)
        self.tableWidget_jobList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.tableWidget_jobList.setFont(font)
        self.tableWidget_jobList.setToolTip("")
        self.tableWidget_jobList.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget_jobList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_jobList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_jobList.setProperty("showDropIndicator", False)
        self.tableWidget_jobList.setDragDropOverwriteMode(False)
        self.tableWidget_jobList.setAlternatingRowColors(True)
        self.tableWidget_jobList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tableWidget_jobList.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableWidget_jobList.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_jobList.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableWidget_jobList.setShowGrid(True)
        self.tableWidget_jobList.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_jobList.setWordWrap(True)
        self.tableWidget_jobList.setCornerButtonEnabled(True)
        self.tableWidget_jobList.setRowCount(100)
        self.tableWidget_jobList.setColumnCount(26)
        self.tableWidget_jobList.setObjectName("tableWidget_jobList")
        self.tableWidget_jobList.setColumnCount(26)
        self.tableWidget_jobList.setRowCount(100)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_jobList.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_jobList.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_jobList.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_jobList.setItem(2, 0, item)
        self.tableWidget_jobList.horizontalHeader().setVisible(True)
        self.tableWidget_jobList.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_jobList.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_jobList.horizontalHeader().setHighlightSections(True)
        self.tableWidget_jobList.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_jobList.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_jobList.verticalHeader().setVisible(False)
        self.tableWidget_jobList.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_jobList.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_5.addWidget(self.tableWidget_jobList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_keisuu = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_keisuu.sizePolicy().hasHeightForWidth())
        self.label_keisuu.setSizePolicy(sizePolicy)
        self.label_keisuu.setObjectName("label_keisuu")
        self.horizontalLayout.addWidget(self.label_keisuu)
        self.lineEdit_keisuu = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_keisuu.sizePolicy().hasHeightForWidth())
        self.lineEdit_keisuu.setSizePolicy(sizePolicy)
        self.lineEdit_keisuu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_keisuu.setObjectName("lineEdit_keisuu")
        self.horizontalLayout.addWidget(self.lineEdit_keisuu)
        self.pushButton_Calc = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Calc.sizePolicy().hasHeightForWidth())
        self.pushButton_Calc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_Calc.setFont(font)
        self.pushButton_Calc.setObjectName("pushButton_Calc")
        self.horizontalLayout.addWidget(self.pushButton_Calc)
        self.pushButton_csvout = QtGui.QPushButton(self.centralWidget)
        self.pushButton_csvout.setObjectName("pushButton_csvout")
        self.horizontalLayout.addWidget(self.pushButton_csvout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.label = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.textEdit_Result = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Result.sizePolicy().hasHeightForWidth())
        self.textEdit_Result.setSizePolicy(sizePolicy)
        self.textEdit_Result.setMinimumSize(QtCore.QSize(0, 120))
        self.textEdit_Result.setMaximumSize(QtCore.QSize(16777215, 240))
        self.textEdit_Result.setObjectName("textEdit_Result")
        self.verticalLayout_4.addWidget(self.textEdit_Result)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_calcclear = QtGui.QPushButton(self.centralWidget)
        self.pushButton_calcclear.setObjectName("pushButton_calcclear")
        self.horizontalLayout_2.addWidget(self.pushButton_calcclear)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1474, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget_Comannds.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Deadlinecalc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_EndDate.setText(QtGui.QApplication.translate("MainWindow", "EndDate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SubDate.setText(QtGui.QApplication.translate("MainWindow", "SubDate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_username.setText(QtGui.QApplication.translate("MainWindow", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ProjectName.setText(QtGui.QApplication.translate("MainWindow", "Projectname:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Reloaduser.setText(QtGui.QApplication.translate("MainWindow", "Reload user and Project", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Comannds.setTabText(self.tabWidget_Comannds.indexOf(self.tab_Project), QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "↓ここにJobIDをペースト", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Comannds.setTabText(self.tabWidget_Comannds.indexOf(self.tab_jobID), QtGui.QApplication.translate("MainWindow", "jobID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Comannds.setTabToolTip(self.tabWidget_Comannds.indexOf(self.tab_jobID), QtGui.QApplication.translate("MainWindow", "プロジェクトから選ぶか、ジョブIDコピペするか選んでね", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Search.setText(QtGui.QApplication.translate("MainWindow", "Search!!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_jobs.setText(QtGui.QApplication.translate("MainWindow", "Job search Results:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.setSortingEnabled(True)
        self.tableWidget_jobList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "JobName", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "JobID", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "UserName", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "SubMachine", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "SubDate", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "FinDate", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "FrameList", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("MainWindow", "C_Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("MainWindow", "Chunk", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("MainWindow", "OutDir", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("MainWindow", "TotalTaskTime", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("MainWindow", "JobPrice", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_jobList.isSortingEnabled()
        self.tableWidget_jobList.setSortingEnabled(False)
        self.tableWidget_jobList.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "off 例", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "Sweets_360rot_MOMO_FullMuki", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 2).setText(QtGui.QApplication.translate("MainWindow", "kuboe", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 4).setText(QtGui.QApplication.translate("MainWindow", "T7910-02", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 5).setText(QtGui.QApplication.translate("MainWindow", "2017/09/06 22:57:08", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 6).setText(QtGui.QApplication.translate("MainWindow", "2017/09/07 10:02:22", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 7).setText(QtGui.QApplication.translate("MainWindow", "0-15", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 8).setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 9).setText(QtGui.QApplication.translate("MainWindow", "3dsmax", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(0, 11).setText(QtGui.QApplication.translate("MainWindow", "さむしんぐ！", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "on 例", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "5870bc4b51c3d020a84efcb1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_jobList.setSortingEnabled(__sortingEnabled)
        self.label_keisuu.setText(QtGui.QApplication.translate("MainWindow", "keisuu:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Calc.setText(QtGui.QApplication.translate("MainWindow", "Calculate!!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_csvout.setText(QtGui.QApplication.translate("MainWindow", "CSV output", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Calc Result:", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_Result.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_calcclear.setText(QtGui.QApplication.translate("MainWindow", "clear Result", None, QtGui.QApplication.UnicodeUTF8))

